# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='emails',
            field=models.EmailField(default=None, max_length=50, verbose_name='\u7535\u5b50\u90ae\u4ef6'),
        ),
    ]
