# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0002_userinfo_emails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date'], 'verbose_name': '\u4f1a\u8bae\u5ba4\u9884\u5b9a\u7ba1\u7406', 'verbose_name_plural': '\u4f1a\u8bae\u5ba4\u9884\u5b9a\u7ba1\u7406'},
        ),
        migrations.AlterModelOptions(
            name='meetingroom',
            options={'verbose_name': '\u4f1a\u8bae\u5ba4\u7ba1\u7406', 'verbose_name_plural': '\u4f1a\u8bae\u5ba4\u7ba1\u7406'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '\u7528\u6237\u7ba1\u7406', 'verbose_name_plural': '\u7528\u6237\u7ba1\u7406'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.IntegerField(choices=[(8, '8:00'), (9, '9:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00')], verbose_name='\u9884\u5b9a\u65f6\u95f4\u6bb5'),
        ),
    ]
